// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectPlanner.Data;

#nullable disable

namespace ProjectPlanner.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240424083258_AddNullableDescription")]
    partial class AddNullableDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectPlanner.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Create biggest bomb ever",
                            Name = "Mahatan Project"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Put man on the moon",
                            Name = "Apollo Project"
                        });
                });

            modelBuilder.Entity("ProjectPlanner.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2024, 4, 24, 9, 32, 57, 861, DateTimeKind.Local).AddTicks(7682),
                            Description = "Succesfully split a atom",
                            Priority = "Medium",
                            ProjectId = 1,
                            Status = "New",
                            Title = "Split Atom"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2024, 4, 24, 9, 32, 57, 861, DateTimeKind.Local).AddTicks(7730),
                            Description = "Find plutunium for the bomb",
                            Priority = "High",
                            ProjectId = 1,
                            Status = "New",
                            Title = "Find Plutonium"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2024, 4, 24, 9, 32, 57, 861, DateTimeKind.Local).AddTicks(7733),
                            Description = "Find someone willingly to go to the moon",
                            Priority = "Low",
                            ProjectId = 2,
                            Status = "New",
                            Title = "Find Astronaut"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2024, 4, 24, 9, 32, 57, 861, DateTimeKind.Local).AddTicks(7736),
                            Description = "Create engine with w16 orientation",
                            Priority = "Medium",
                            ProjectId = 4,
                            Status = "New",
                            Title = "Create w16 engine"
                        });
                });

            modelBuilder.Entity("ProjectPlanner.Models.Ticket", b =>
                {
                    b.HasOne("ProjectPlanner.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
